[MFLOG|0|2025-04-17T18:38:46.808280Z|runtime|5a4c8336-b4c5-432d-a5ba-5dcf4fc5ac6d]<flow TrainingFlow step start> failed:
[MFLOG|0|2025-04-17T18:38:46.810783Z|runtime|599c378b-64a3-4ca3-80ae-b59cc48f14b3]    Internal error
[MFLOG|0|2025-04-17T18:38:46.811738Z|runtime|94d9037c-354d-4225-bd30-da6a043026e7]Traceback (most recent call last):
[MFLOG|0|2025-04-17T18:38:46.811806Z|runtime|de300501-6771-47c4-a99a-4ef59d5a5736]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/cli.py", line 611, in main
[MFLOG|0|2025-04-17T18:38:46.811848Z|runtime|7cecf8d3-76ca-4b0e-9452-ad4a3a66f3f4]    start(auto_envvar_prefix="METAFLOW", obj=state)
[MFLOG|0|2025-04-17T18:38:46.811877Z|runtime|410a725f-2bd9-404c-8f0a-8115ba511483]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/_vendor/click/core.py", line 829, in __call__
[MFLOG|0|2025-04-17T18:38:46.811904Z|runtime|e3ab13c6-cf6f-4774-85f8-18c7602c8475]    return self.main(args, kwargs)
[MFLOG|0|2025-04-17T18:38:46.914347Z|runtime|a36ca071-1b20-49c9-b9fb-7bfffc84bbcd]           ^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-17T18:38:46.914486Z|runtime|75a7d45c-c14d-4c13-8d31-a44604e1cf3e]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/_vendor/click/core.py", line 782, in main
[MFLOG|0|2025-04-17T18:38:46.914532Z|runtime|ac444cb3-1db1-419e-90fa-0892b7f5675f]    rv = self.invoke(ctx)
[MFLOG|0|2025-04-17T18:38:46.914554Z|runtime|785fd139-6bcd-4f1a-9032-ab2a2aea444c]         ^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-17T18:38:46.914578Z|runtime|4deadfa7-9e42-4634-989a-0fa380d8e11e]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/cli_components/utils.py", line 69, in invoke
[MFLOG|0|2025-04-17T18:38:46.914599Z|runtime|1df1aab3-2559-4327-818f-22da82255b4c]    return _process_result(sub_ctx.command.invoke(sub_ctx))
[MFLOG|0|2025-04-17T18:38:46.914618Z|runtime|3c518528-a656-41e4-97e5-ae8db07bb0fc]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-17T18:38:46.914639Z|runtime|d7fd5bed-764a-4bc5-9700-65c23d5becf1]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/_vendor/click/core.py", line 1066, in invoke
[MFLOG|0|2025-04-17T18:38:46.914659Z|runtime|94bb2489-3ccb-47eb-915b-5c574470794e]    return ctx.invoke(self.callback, ctx.params)
[MFLOG|0|2025-04-17T18:38:46.914676Z|runtime|3e5850d8-add7-43ac-9798-2af2f4d0561f]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-17T18:38:46.914694Z|runtime|8364d386-d755-4043-974e-ff5b30695c09]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/_vendor/click/core.py", line 610, in invoke
[MFLOG|0|2025-04-17T18:38:46.914711Z|runtime|511d73c8-0749-4e38-97aa-dd273482d908]    return callback(args, kwargs)
[MFLOG|0|2025-04-17T18:38:46.914729Z|runtime|b5cba29c-eea1-4d30-b015-f9afa719de98]           ^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-17T18:38:46.914748Z|runtime|b41b444a-71b4-4910-a6ca-72f0d282678c]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/tracing/__init__.py", line 27, in wrapper_func
[MFLOG|0|2025-04-17T18:38:46.914766Z|runtime|fd1b35cb-085f-4be7-90b4-dd2b3882ab9f]    return func(args, kwargs)
[MFLOG|0|2025-04-17T18:38:46.914782Z|runtime|f32af246-ec08-4581-a62f-272096ffb920]           ^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-17T18:38:46.914798Z|runtime|18fece77-973c-460a-b343-d8d1fbe13a8f]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/_vendor/click/decorators.py", line 21, in new_func
[MFLOG|0|2025-04-17T18:38:46.914815Z|runtime|af29b44e-c3ca-4b20-9d39-112491511350]    return f(get_current_context(), args, kwargs)
[MFLOG|0|2025-04-17T18:38:46.914832Z|runtime|e13f5bf0-fe01-42cf-b875-a8273d87001e]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-17T18:38:46.914850Z|runtime|f03a1ed3-3ae2-489f-9480-f72510916b45]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/cli_components/step_cmd.py", line 167, in step
[MFLOG|0|2025-04-17T18:38:46.914870Z|runtime|7f6378f7-dbf5-4a64-8735-0d1cf3cc1e68]    task.run_step(
[MFLOG|0|2025-04-17T18:38:46.914887Z|runtime|032aaf9e-e5d8-42bc-ab6f-4d932e4ed3aa]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/task.py", line 672, in run_step
[MFLOG|0|2025-04-17T18:38:46.914903Z|runtime|fd97baff-980f-4947-80d7-928bf2db9df8]    self._exec_step_function(step_func)
[MFLOG|0|2025-04-17T18:38:46.914922Z|runtime|4394ce97-0a58-41bc-9a27-3fdc1159eca0]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/metaflow/task.py", line 62, in _exec_step_function
[MFLOG|0|2025-04-17T18:38:46.914941Z|runtime|b1ca6544-6730-4f26-bda7-a9ac8387613a]    step_function()
[MFLOG|0|2025-04-17T18:38:46.914959Z|runtime|44273772-4650-474c-839e-5318faedd99a]  File "/Users/jahnavipaliwal/Desktop/ML_Ops/MLOps/Labs/Lab6/src/trainingflow.py", line 14, in start
[MFLOG|0|2025-04-17T18:38:46.914975Z|runtime|398c11a0-eed8-4fb9-8ff1-99944db7d2db]    self.df = pd.read_csv('bagpack/train.csv')
[MFLOG|0|2025-04-17T18:38:46.914996Z|runtime|9646438f-b33e-4633-916b-1c499f6866be]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-17T18:38:46.915011Z|runtime|8b20eb03-6428-4eb0-9e02-d505a3a37f79]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
[MFLOG|0|2025-04-17T18:38:46.915031Z|runtime|e22028d4-5f86-471c-8b55-8f74f793cd0b]    return _read(filepath_or_buffer, kwds)
[MFLOG|0|2025-04-17T18:38:46.915048Z|runtime|4cf0f4b3-5acd-45a1-8625-e53944dba459]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-17T18:38:46.915063Z|runtime|4e085897-870d-4d69-8395-e06fb2635803]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 620, in _read
[MFLOG|0|2025-04-17T18:38:46.915078Z|runtime|92bc31c8-8248-4a1e-b008-9dbb2ed45daf]    parser = TextFileReader(filepath_or_buffer, kwds)
[MFLOG|0|2025-04-17T18:38:46.915093Z|runtime|16713ec8-b849-4d9a-bd9e-68e1aae05c09]             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-17T18:38:46.915109Z|runtime|3e1be737-c04b-4290-bd39-c17ce229ec87]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
[MFLOG|0|2025-04-17T18:38:46.915124Z|runtime|75f2ce42-144e-4ce7-b026-81cb036f5600]    self._engine = self._make_engine(f, self.engine)
[MFLOG|0|2025-04-17T18:38:46.915140Z|runtime|1df9b84f-3e19-4f64-9275-2a37b08bc397]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2025-04-17T18:38:46.915156Z|runtime|94202f4e-7bf0-42f5-ab2f-c06302338b1b]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
[MFLOG|0|2025-04-17T18:38:46.915171Z|runtime|ff465176-41b3-4da3-911e-4f0e5e7afacb]    self.handles = get_handle(
[MFLOG|0|2025-04-17T18:38:46.915191Z|runtime|b7812295-91d1-49b2-914f-e1b5da37accd]                   ^^^^^^^^^^^
[MFLOG|0|2025-04-17T18:38:46.915206Z|runtime|d7c066c1-367e-4dbf-b9cd-e482395e1a4a]  File "/opt/anaconda3/envs/mlops/lib/python3.12/site-packages/pandas/io/common.py", line 873, in get_handle
[MFLOG|0|2025-04-17T18:38:46.915222Z|runtime|ae6ab763-e07c-4f29-a890-c0c3bae2e9a9]    handle = open(
[MFLOG|0|2025-04-17T18:38:46.915238Z|runtime|6f21c149-778e-4b7c-aef9-ccb4e3fb2737]             ^^^^^
[MFLOG|0|2025-04-17T18:38:46.915253Z|runtime|abf90f8e-f3f8-467a-9965-1606ba657f51]FileNotFoundError: [Errno 2] No such file or directory: 'bagpack/train.csv'
[MFLOG|0|2025-04-17T18:38:46.915269Z|runtime|75f2a835-e288-400a-a97a-9e241dbc0784]
[MFLOG|0|2025-04-17T18:38:46.915584Z|runtime|f10069f7-0202-487b-a5a3-68385df3ff95]Task failed.